CREATE TABLE IF NOT EXISTS CUSTOMER (
CUSTOMER_ID INT(10) auto_increment,
NAME VARCHAR(50),
ADDRESS VARCHAR(100),
TELEPHONE_NO VARCHAR(20),
EMAIL_ADDRESS VARCHAR(50),
FAX_NUMBER VARCHAR(50),
PRIMARY KEY (CUSTOMER_ID),
UNIQUE (NAME)
);

CREATE TABLE IF NOT EXISTS SUPPLIER (
ID INT(10) auto_increment,
NAME VARCHAR(50),
ADDRESS VARCHAR(100),
TELEPHONE_NO VARCHAR(20),
EMAIL_ADDRESS VARCHAR(50),
FAX_NUMBER VARCHAR(50),
PRIMARY KEY (ID),
UNIQUE (NAME)
);

CREATE TABLE IF NOT EXISTS INVENTORY(
ITEM_CODE VARCHAR(100),
NAME VARCHAR(100),
DESCRIPTION VARCHAR(200),
EACH_PRICE INT(10),
AMOUNT INT(10),
PRIMARY KEY (ITEM_CODE)
);

CREATE TABLE IF NOT EXISTS GRN(
GRN_NO INT(10) auto_increment,
SUPPLIER_ID INT(10),
PURCHASING_DATE DATE,
TERMS VARCHAR (10),
PRIMARY KEY (GRN_NO),
FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS GRN_ITEMS(
GRN_NO INT(10),
ITEM_CODE VARCHAR(100),
QUANTITY INT(10),
ITEM_PRICE INT(10),
FOREIGN KEY (GRN_NO) REFERENCES GRN (GRN_NO) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (ITEM_CODE) REFERENCES INVENTORY (ITEM_CODE) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS INVOICE(
INVOICE_NO INT (10) auto_increment,
CUSTOMER_ID INT(10),
ITEM_CODE VARCHAR(100),
QUANTITY INT(10),
PRIMARY KEY (INVOICE_NO),
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (ITEM_CODE) REFERENCES INVENTORY(ITEM_CODE) ON DELETE CASCADE ON UPDATE CASCADE
);