swagger: "2.0"
info:
  title: user-manager
  version: 1.0.0
paths:
  /user/delete/{user-id}:
    delete:
      summary: delete a user
      produces:
        - application/json
      parameters:
        - name: user-id
          required: true
          type: string
          in: path
      consumes:
        - application/json
      responses:
        204:
          description: user deleted
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /user/update/{user-id}:
    post:
      summary: update a user
      produces:
        - application/json
      parameters:
        - name: user-id
          required: true
          type: string
          in: path
        - schema:
            type: object
          description: Request Body
          name: Payload
          required: false
          in: body
      consumes:
        - application/json
      responses:
        204:
          description: user updated
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /user/add:
    put:
      summary: add a user
      produces:
        - application/json
      parameters:
        - description: user name
          name: name
          required: false
          type: string
          in: formData
        - description: user address
          name: address
          required: false
          type: string
          in: formData
        - description: user email
          name: email-address
          required: false
          type: string
          in: formData
        - description: user phone number
          name: phone-number
          required: false
          type: string
          in: formData
        - description: user fax number
          name: fax-number
          required: false
          type: string
          in: formData
      consumes:
        - application/json
      responses:
        204:
          description:  user added
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /user/getall:
    get:
      summary: get all users
      produces:
        - application/json
      consumes:
        - application/json
      responses:
        200:
          description: An array of user
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /user/get/{user-id}:
    get:
      summary: get user data by id
      produces:
        - application/json
      parameters:
        - name: user-id
          required: true
          type: string
          in: path
      consumes:
        - application/json
      responses:
        200:
          description: user response
          schema:
            $ref: "#/definitions/User"
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

################################################################################
#                                 Definitions                                  #
################################################################################
definitions:
  User:
    type: object
    description: user data
    properties:
      id:
        type: string
        description: user id
      name:
        type: string
        description: user name
      address:
        type: string
        description: user address
      emailAddress:
        type: string
        description: user email address
      phoneNumber:
        type: string
        description: user phone number
      faxNumber:
        type: string
        description: user fax number
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
